# Generated by Django 5.0.7 on 2024-07-16 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('air_temp', models.IntegerField()),
                ('air_pressure', models.IntegerField()),
                ('cloud_cover', models.IntegerField()),
                ('humidity', models.IntegerField()),
                ('precipitation', models.IntegerField()),
                ('visibility', models.IntegerField()),
                ('water_temp', models.IntegerField()),
                ('wind_speed', models.IntegerField()),
                ('wind_dir', models.IntegerField()),
            ],
        ),
    ]
