# Generated by Django 5.0.7 on 2024-07-18 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weather',
            options={'ordering': ['-added']},
        ),
        migrations.RemoveField(
            model_name='weather',
            name='air_pressure',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='air_temp',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='cloud_cover',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='humidity',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='precipitation',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='visibility',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='water_temp',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='wind_dir',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='wind_speed',
        ),
        migrations.AddField(
            model_name='weather',
            name='added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='weather',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='weather',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='lon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
